export enum PermissionStatus {
  CHECKING = "CHECKING",
  GRANTED = "GRANTED",
  DENIED = "DENIED",
  BLACKED = "BLACKED",
  LIMITED = "LIMITED",
  UNAVAILABLE = "UNAVAILABLE",
  UNDETERMINED = "UNDETERMINED",
}
